# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_sub_catogery', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_topic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_topic_name', models.CharField(max_length=200)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharpurskill.Main_Category')),
            ],
        ),
        migrations.AddField(
            model_name='course_types',
            name='sub_sub_topic',
            field=models.ManyToManyField(to='sharpurskill.Sub_Category'),
        ),
        migrations.AddField(
            model_name='course',
            name='Sub_Topic',
            field=models.ManyToManyField(to='sharpurskill.Sub_Category'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharpurskill.Course_Types'),
        ),
        migrations.AddField(
            model_name='course',
            name='main_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharpurskill.Main_Category'),
        ),
    ]
